displayName=Colossal Wyrm Agility
author=Proddy
description=A plugin to help AFKing Colossal Wyrm Agility.
tags=colossal,wyrm,agility,afk
version=1.2.1
plugins=org.zhbot.colossal_wyrm_agility.ColossalWyrmAgilityPlugin
build=standard